### PR TITLE
better error handling when incorrect config file

### LINKED ISSUE #7: Error loading plugin: unexpected EOF
I `go get` the repo, build and had an issue. Here are my steps: 

```
$ go get github.com/intelsdi-x/snap-plugin-collector-nova
$ go build 
$ snapctl plugin load ./snap-plugin-collector-nova
```

Error from `snapd -t 0 -l 2` is: 

```
INFO[1062] API request                                   _module=_mgmt-rest index=18 method=GET url=/v1/tribe/agreements
INFO[1062] API response                                  _module=_mgmt-rest index=18 method=GET status=Not Found status-code=404 url=/v1/tribe/agreements
INFO[1062] API request                                   _module=_mgmt-rest index=19 method=POST url=/v1/plugins
INFO[1064] Loading plugin: /var/folders/2j/q3vl1w011yn0w4j7294btg280000gp/T/830713433/snap-plugin-collector-nova  _module=_mgmt-rest
INFO[1064] plugin load called                            _block=load _module=control
INFO[1064] plugin load called                            _block=load-plugin _module=control-plugin-mgr path=snap-plugin-collector-nova
ERRO[1064] error in getting metric types                 _block=load-plugin _module=control-plugin-mgr error=unexpected EOF plugin-type=collector
ERRO[1064] unexpected EOF                                _module=_mgmt-rest
INFO[1064] API response                                  _module=_mgmt-rest index=19 method=POST status=Internal Server Error status-code=500 url=/v1/plugins
```

Error message from `snapctl` is same as title: `Error loading plugin: unexpected EOF`

### PR DESCRIPTION
**Pull request by daria-lewandowska**
Closes #7

Summary of changes:
-change only panic: `panic(fmt.Errorf("plugin initalization failed : [%v]", err))`
for `return fmt.Errorf(err.Error())`, because panic (don't know why causes Unexpected EOF 

Testing done:
-Integration tests

Before: 
`Error loading plugin:`
 `Unexpected EOF `

After: 
`Error loading plugin:`
`GetMetricTypes call error : Cannot find openstack_user in Global Config`

### CODE REVIEW

File: novaplugin/plugin.go [hunk 1]
```diff
@@ -288,7 +288,7 @@ func (self *NovaPlugin) init(cfg interface{}) error {
 	err := ReadConfig(cfg, &self.config)
 
 	if err != nil {
-		panic(fmt.Errorf("plugin initalization failed : [%v]", err))
+		return fmt.Errorf(err.Error())
```
Comment (marcin-krolik) [inline novaplugin/plugin.go]: why not `return err` instead?

**Comment by marcin-krolik** [comment]
LGTM
